ALTER TABLE audit_cache
  ALTER COLUMN result DROP NOT NULL;

ALTER TABLE audit_cache
  ADD COLUMN IF NOT EXISTS compression TEXT;

ALTER TABLE audit_cache
  ADD COLUMN IF NOT EXISTS compressed_result BYTEA;

ALTER TABLE audit_cache
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

ALTER TABLE audit_cache
  ADD COLUMN IF NOT EXISTS input_chars INTEGER;

ALTER TABLE audit_cache
  ADD COLUMN IF NOT EXISTS output_chars INTEGER;

ALTER TABLE audit_cache
  ADD COLUMN IF NOT EXISTS cache_mode TEXT;

ALTER TABLE audit_cache
  ADD COLUMN IF NOT EXISTS estimated_cost NUMERIC(12,6);

CREATE TABLE IF NOT EXISTS audit_costs (
  audit_id INTEGER PRIMARY KEY,
  prompt_mode TEXT,
  model TEXT,
  cache_hit BOOLEAN NOT NULL DEFAULT FALSE,
  input_chars INTEGER NOT NULL DEFAULT 0,
  output_chars INTEGER NOT NULL DEFAULT 0,
  ai_cost NUMERIC(12,6) NOT NULL DEFAULT 0,
  total_cost NUMERIC(12,6) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
